version: "3.7"

services:
  prestashop:
    image: prestashop/prestashop:8.1
    container_name: prestashop_app
    ports:
      - "8080:80"
    environment:
      # jeśli chcesz pominąć web-installer i auto zainstalować ustaw PS_INSTALL_AUTO: "1"
      PS_DEV_MODE: "0"
      PS_INSTALL_AUTO: "1"
      DB_SERVER: db
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWORD: root
      PS_ERASE_DB: "0"
    volumes:
      - ./prestashop:/var/www/html    # TU będziesz mieć kod Presty (edytowalny)
      - prestashop_uploads:/var/www/html/img
      - prestashop_modules:/var/www/html/modules
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: prestashop_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prestashop
    volumes:
      - prestashop_db_data:/var/lib/mysql

volumes:
  prestashop_db_data:
  prestashop_uploads:
  prestashop_modules:
